apiVersion: batch/v1
kind: CronJob
metadata:
  name: markets-cert-alerts
  namespace: openshift-monitoring
spec:
  # cron job is scheduled based on UTC 9:30 EST Mon to Fri
  schedule: '30 14 * * 1-5'
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: OnFailure
          serviceAccountName: alertmanager-main
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - name: tls-cert-alerts
              image: 'registry.redhat.io/openshift4/ose-tools-rhel8:v4.9'
              command:
                - /bin/sh
                - /configmap/cert-alerts-check.sh
              resources: {}
              volumeMounts:
                - name: configmap
                  mountPath: /configmap
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          serviceAccount: alertmanager-main
          volumes:
            - name: configmap
              configMap:
                name: tls-cert-alerts
                defaultMode: 420
          dnsPolicy: ClusterFirst
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
