apiVersion: v1
kind: ConfigMap
metadata:
  name: infinispan-operator-config
data:
  grafana.dashboard.namespace: dtse
  grafana.dashboard.name: infinispan
  grafana.dashboard.monitoring.key: middleware

