apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: async-cache-xml-1
spec:
  adminAuth:
    secretName: basic-auth
  clusterName: rh-datagrid
  name: async-cache-xml-1
  template: >-
      <distributed-cache name="async-cache-xml-1" owners="2" mode="ASYNC" statistics="true">
        <encoding media-type="application/x-protostream"/>
        <state-transfer enabled="false"/>
        <memory>
          <binary eviction="MEMORY" size="400000000"/> <!-- 400 MB -->
        </memory>
        <expiration lifespan="600000"/> <!-- 10 min -->
      </distributed-cache>