apiVersion: v1
kind: ConfigMap
metadata:
  name: batch-cache
data:
  batch: |
    create cache --template=org.infinispan.DIST_ASYNC asynccache
    put --cache=asynccache hello world
    put --cache=asynccache hola mundo
    create cache --template=org.infinispan.DIST_SYNC synccache
    put --cache=synccache hello world
    put --cache=synccache hola mundo