apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: rh-datagrid
  annotations:
    infinispan.org/monitoring: 'true'
spec:
  replicas: 2
  service:
    type: DataGrid
    replicationFactor: 2
  autoscale:
    maxMemUsagePercent: 70
    maxReplicas: 5
    minMemUsagePercent: 30
    minReplicas: 2
  security:
    endpointSecretName: endpoint-identities
    endpointEncryption:
        type: Secret
        certSecretName: tls-secret
  container:
    extraJvmOpts: "-XX:NativeMemoryTracking=summary"
    cpu: "2000m"
    memory: 1Gi
  logging:
    categories:
      org.infinispan: trace
      org.jgroups: trace
  expose:
    type: LoadBalancer
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: infinispan-pod
              clusterName: rh-datagrid
              infinispan_cr: rh-datagrid
          topologyKey: "kubernetes.io/hostname"
