apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: sessions
spec:
  adminAuth:
    secretName: basic-auth
  clusterName: rh-datagrid
  name: sessions
  template: >-
    <distributed-cache name="sessions" statistics="true">
      <encoding media-type="application/x-protostream"/>
      <expiration lifespan="1800000"/> <!-- 30 min -->
    </distributed-cache>
