apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: session-cache
spec:
  adminAuth:
    secretName: basic-auth
  clusterName: rh-datagrid
  name: session-cache
  template: >-
    <distributed-cache name="session-cache" statistics="true">
      <encoding media-type="application/x-java-serialized-object"/>
      <!-- encoding media-type="application/x-protostream"/ -->
      <expiration lifespan="1800000"/> <!-- 30 min -->
    </distributed-cache>
