apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: sync-cache-xml
spec:
  adminAuth:
    secretName: basic-auth
  clusterName: rh-datagrid
  name: sync-cache-xml
  template: >-
      <distributed-cache name="sync-cache-xml" owners="2" mode="SYNC" statistics="true">
        <encoding media-type="application/x-java-object"/>
        <!-- encoding media-type="application/x-protostream"/ -->
        <state-transfer enabled="false"/>
        <memory>
          <binary eviction="MEMORY" size="400000000"/> <!-- 400 MB -->
        </memory>
        <expiration lifespan="600000"/> <!-- 10 min -->
        <persistence>
          <file-store/>
        </persistence>
      </distributed-cache>
