apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: temperature
spec:
  adminAuth:
    secretName: basic-auth
  clusterName: rh-datagrid
  name: temperature
  template: >-
    <distributed-cache name="temperature" remote-timeout="17500" statistics="true">
      <locking acquire-timeout="15000" striping="false" concurrency-level="1000"/>
      <!-- encoding media-type="application/x-protostream"/ -->
      <encoding>
        <key media-type="application/x-java-serialized-object"/>
        <value media-type="application/x-java-serialized-object"/>
      </encoding>
      <state-transfer timeout="60000"/>
    </distributed-cache>
